spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true # data.sql 수행
  sql:
    init:
      encoding: UTF-8
      mode: always
      data-locations: classpath*:db/data.sql

secret:
  key: local-secret@!

cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1

logging:
  level:
    org:
      hibernate.type.descriptor.sql: TRACE
      springframework.http: TRACE