### Get Token
POST http://localhost:8080/sign-in
Content-Type: application/json;charset=UTF-8

{
  "email": "user@myunjuk.kr",
  "password": "userpw"
}

> {% //response handler
client.global.set("access_token", response.body.accessToken);
client.log(client.global.get("access_token"));
%}

###
GET http://localhost:8080/profile
Content-Type: application/json;charset=UTF-8
X-AUTH-TOKEN: {{access_token}}

